import {
    //NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'dashboard',
        path: '/dashboard',
        title: 'Dashboard',
        translateKey: 'nav.dashboard',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },

    /** Example purpose only, please remove */
    {
        key: 'proiecte',
        path: '/proiecte',
        title: 'Proiecte',
        translateKey: 'nav.proiecte',
        icon: 'singleMenu',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },

    {
        key: 'documente',
        path: '/documente',
        title: 'Documente',
        translateKey: 'nav.documente',
        icon: 'singleMenu',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'sarcini',
        path: '/sarcini',
        title: 'Sarcini',
        translateKey: 'nav.sarcini',
        icon: 'singleMenu',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'piese',
        path: '/piese',
        title: 'Piese',
        translateKey: 'nav.piese',
        icon: 'singleMenu',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'clienti',
        path: '/clienti',
        title: 'Clienti',
        translateKey: 'nav.clienti',
        icon: 'singleMenu',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'chat',
        path: '/chat',
        title: 'Chat',
        translateKey: 'nav.chat',
        icon: 'singleMenu',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },

    {
        key: 'setariPlatforma',
        path: '/setari-platforma',
        title: 'Setari Platforma',
        translateKey: 'nav.setari-platforma.collapseMenu',
        icon: 'collapseMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'utilizatori.item1',
                path: '/utilizatori',
                title: 'Utilizatori',
                translateKey: 'nav.utilizatori',
                icon: 'singleMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'roluri.item1',
                path: '/roluri',
                title: 'Roluri',
                translateKey: 'nav.roluri',
                icon: 'singleMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'statusuri.item2',
                path: '/statusuri',
                title: 'Statusuri',
                translateKey: 'nav.statusuri.item2',
                icon: 'singleMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'sabloane.item3',
        path: '/sabloane',
        title: 'Sabloane',
        translateKey: 'nav.sabloane.collapseMenu',
        icon: 'collapseMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'sabloane-documente.item1',
                path: '/sabloane-documente',
                title: 'Documente',
                translateKey: 'nav.sabloane-documente.item1',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'sabloane-sarcini.item2',
                path: '/sabloane-sarcini',
                title: 'Sarcini',
                translateKey: 'nav.sabloane-sarcini.item2',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'logs.item4',
        path: '/logs',
        title: 'Logs',
        translateKey: 'nav.logs.item4',
        icon: 'singleMenu',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'setari-cont.item5',
        path: '/setari-cont',
        title: 'Setari Cont',
        translateKey: 'nav.setari-cont.item5',
        icon: 'singleMenu',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
]

export default navigationConfig
